### ISSUE TITLE
Должно быть консольное приложение

### ISSUE THREAD

**Issue by YegorMan** [Bareen86/Calculator#1]
Круто, что умеешь создавать приложения с UI. Но, все-таки, в этом задании хочется увидеть умение работы с консольным приложением. Необходимо переделать на консольное приложение.

**Comment by Bareen86** [comment]
С UI Переделал на консоль
https://github.com/Bareen86/ConsoleCalculator
Можете еще подсказать: как в этот репозиторий добавить новый проект(Консольный калькулятор)?

**Comment by YegorMan** [comment]
Я так понял, у тебя все получилось?
Чтобы добавить новый проект, необходимо открыть текущее решение в VisualStudio, и щелчком правой кнопкой мыши по решению выбрать "добавить новый проект". После этого git должен увидеть новые файлы. Если этого не произошло, необходимо пометить неотслеживаемые файлы как отслеживаемые.
Ключевые слова для поиска как это сделать,
git status
untracked files
tracked files
git add
